### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by xTridentSecurityx** [DanBot-Hosting/DBH-Bot-API#4]
getting an error when i try to use the import after installing the wrapper 

```py
import dbhwrapper
from dbhwrapper import bot
```
it says this error

```json
Traceback (most recent call last):
  File "/home/container/main.py", line 136, in <module>
    from dbhwrapper import bot
ModuleNotFoundError: No module named 'dbhwrapper'
Exception ignored in: <function CleanAsyncClient.__del__ at 0x7f3e91168860>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/roblox/utilities/requests.py", line 36, in __del__
  File "/usr/local/lib/python3.11/asyncio/events.py", line 761, in get_event_loop_policy
  File "/usr/local/lib/python3.11/asyncio/events.py", line 754, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
```

cant use dbh-bot-wrapper either because of the dash.

what do i set so i can import it?

**Comment by SpreadSheets600** [comment]
> getting an error when i try to use the import after installing the wrapper
> 
> ```python
> import dbhwrapper
> from dbhwrapper import bot
> ```
> 
> it says this error
> 
> ```json
> Traceback (most recent call last):
>   File "/home/container/main.py", line 136, in <module>
>     from dbhwrapper import bot
> ModuleNotFoundError: No module named 'dbhwrapper'
> Exception ignored in: <function CleanAsyncClient.__del__ at 0x7f3e91168860>
> Traceback (most recent call last):
>   File "/home/container/.local/lib/python3.11/site-packages/roblox/utilities/requests.py", line 36, in __del__
>   File "/usr/local/lib/python3.11/asyncio/events.py", line 761, in get_event_loop_policy
>   File "/usr/local/lib/python3.11/asyncio/events.py", line 754, in _init_event_loop_policy
> ImportError: sys.meta_path is None, Python is likely shutting down
> ```
> 
> cant use dbh-bot-wrapper either because of the dash.
> 
> what do i set so i can import it?

I was about to write about this issue, let me try asking in the server

**Comment by Kyro3400** [comment]
This is the wrong repo to be asking this, but if you check the [dbh-api-wrapper](https://github.com/danbot-hosting/dbh-api-wrapper) in the readme you need to use `danbot-hosting` now

**Comment by DottoXD** [comment]
Closing the issue - wrong repo.
